:toc: left
:stylesheet: ubuntu.css
:linkattrs:
:source-highlighter: pygments
[.text-justify]

== Getting start with SystemVerilog Design

SystemVerilog is a Hardware Description and Verification Language (HDVL) that become popular in many applications today. Actually, SystemVerilog is a evolution of Verilog language, and incorporates the advantages of an intuitive language like C/C++ and the philosophy of a HDL (Hardware Description Language) like VHDL.

So, this tutorial has the objective of show the main concepts and sintax of SystemVerilog, showing some examples with components of digital systems that are important to understand.

== Examples
[.text-justify]
=== link:and_port/and_port.html[A simple component with SystemVerilog]
In this example, we will see the fundamentals of SystemVerilog syntax. The easiest way to start to learn a new language is analyzing a simple component, with few ports. So, in this example is suggested to implement an and port, where we will design the component, make a testbench and observe the results in a modelsim enviroment.
